wget http://weather.unisys.com/hurricane/atlantic/2011H/SEAN/track.dat -O SEAN
wget http://weather.unisys.com/hurricane/atlantic/2011H/RINA/track.dat -O RINA
wget http://weather.unisys.com/hurricane/atlantic/2011H/PHILIPPE/track.dat -O PHILIPPE
wget http://weather.unisys.com/hurricane/atlantic/2011H/OPHELIA/track.dat -O OPHELIA
wget http://weather.unisys.com/hurricane/atlantic/2011H/NATE/track.dat -O NATE
wget http://weather.unisys.com/hurricane/atlantic/2011H/MARIA/track.dat -O MARIA
wget http://weather.unisys.com/hurricane/atlantic/2011H/LEE/track.dat -O LEE
wget http://weather.unisys.com/hurricane/atlantic/2011H/KATIA/track.dat -O KATIA
wget http://weather.unisys.com/hurricane/atlantic/2011H/JOSE/track.dat -O JOSE
wget http://weather.unisys.com/hurricane/atlantic/2011H/TEN/track.dat -O TEN
wget http://weather.unisys.com/hurricane/atlantic/2011H/IRENE/track.dat -O IRENE
wget http://weather.unisys.com/hurricane/atlantic/2011H/HARVEY/track.dat -O HARVEY
wget http://weather.unisys.com/hurricane/atlantic/2011H/GERT/track.dat -O GERT
wget http://weather.unisys.com/hurricane/atlantic/2011H/FRANKLIN/track.dat -O FRANKLIN
wget http://weather.unisys.com/hurricane/atlantic/2011H/EMILY/track.dat -O EMILY
wget http://weather.unisys.com/hurricane/atlantic/2011H/DON/track.dat -O DON
wget http://weather.unisys.com/hurricane/atlantic/2011H/CINDY/track.dat -O CINDY
wget http://weather.unisys.com/hurricane/atlantic/2011H/BRET/track.dat -O BRET
wget http://weather.unisys.com/hurricane/atlantic/2011H/ARLENE/track.dat -O ARLENE
